"""Stage 5: ADAPT_REPORT.md — what was found, what was inferred, what is undetermined.

Confidence in this report is copied from the verification gate (verify.py) and nowhere else.
The must-review list is the point of the whole document: it is the exact set of lines a human
has to look at before a generated agent directory is allowed anywhere near a real model.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from upshift import __version__
from upshift.adapt.extract import ExtractionResult
from upshift.adapt.generate import GenerationResult
from upshift.adapt.inventory import Inventory
from upshift.adapt.verify import ERROR, Verification

CONFIDENCE_MEANING = {
    "high": "verbatim-verified against the cited source",
    "medium": "assembled from cited parts (templated, or citation resolved but text did not)",
    "low": "inferred — not confirmed by any citation that checked out",
}


@dataclass
class CostInfo:
    provider: str
    model: str
    input_tokens: int
    output_tokens: int
    cached_input_tokens: int
    usd: float | None
    run_dir: str
    run_id: str


def _table(rows: list[tuple[str, ...]], headers: tuple[str, ...]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(lines)


def _claim_line(name: str, claim: dict[str, Any]) -> str:
    value = claim.get("value")
    mark = "verified" if claim.get("verified") else claim.get("status", "?")
    citation = claim.get("citation") or "no citation"
    note = f" — {claim['note']}" if claim.get("note") else ""
    return f"- **{name}**: `{value!r}` [{mark}] from `{citation}`{note}"


def render_report(
    *,
    inventory: Inventory,
    extraction: ExtractionResult | None,
    verification: Verification | None,
    generation: GenerationResult | None,
    cost: CostInfo | None,
    out_dir: Path,
    aborted: str | None = None,
) -> str:
    repo = inventory.repo
    lines: list[str] = []
    add = lines.append

    add("# ADAPT_REPORT — generated agent directory")
    add("")
    add(f"- Source: `{repo.origin}`" + (" (shallow clone)" if repo.is_clone else ""))
    add(f"- Commit: `{repo.commit or 'not a git checkout'}`")
    add(f"- Generated: {datetime.now(UTC).isoformat(timespec='seconds')} by upshift "
        f"{__version__} (`upshift adapt`)")
    add(f"- Output: `{out_dir.resolve()}`")
    if cost:
        add(f"- Extraction model: `{cost.model}` via provider `{cost.provider}`")
    add("")
    add("> Generated by a model reading someone else's code. Everything below is a claim with")
    add("> a citation; only the lines marked *verified* were checked mechanically against the")
    add("> source. Review the must-review list before spending money on a run.")
    add("")

    if aborted:
        add("## ABORTED")
        add("")
        add(f"{aborted}")
        add("")
        add("This report is partial: stages after the abort did not run.")
        add("")

    # -- confidence ---------------------------------------------------------
    if verification:
        add("## Confidence per artifact")
        add("")
        add(_table(
            [
                (f"`{artifact}`", level, CONFIDENCE_MEANING[level])
                for artifact, level in sorted(verification.confidence.items())
            ],
            ("artifact", "confidence", "what that means"),
        ))
        add("")
        add(f"Citations checked: {verification.checked} · claims downgraded by the gate: "
            f"{verification.downgraded}")
        add("")

    # -- found / inferred / undetermined ------------------------------------
    if verification:
        data = verification.data
        add("## Found")
        add("")
        for name in ("endpoint", "model", "params", "max_turns"):
            claim = data.get(name) or {}
            add(_claim_line(name, claim))
        prompt = data.get("system_prompt") or {}
        chunks = prompt.get("chunks") or []
        verbatim = sum(1 for c in chunks if c.get("verified") and c.get("kind") == "verbatim")
        add(f"- **system prompt**: {len(chunks)} chunk(s), {verbatim} verbatim-verified")
        for chunk in chunks:
            state = "verified" if chunk.get("verified") else "UNVERIFIED"
            preview = str(chunk.get("text") or "").strip().replace("\n", " ")[:70]
            add(f"  - `{chunk.get('citation')}` [{chunk.get('kind')}/{state}] {preview!r}")
        add(f"- **tools**: {len(data.get('tools') or [])}")
        for tool in data.get("tools") or []:
            state = "verified" if tool.get("verified") else "UNVERIFIED"
            add(f"  - `{tool.get('name')}` from `{tool.get('citation')}` "
                f"[{tool.get('kind')}/{state}] · backend: "
                f"{(tool.get('backend') or {}).get('kind', 'unclear')}")
        add("")

        add("## Inferred (no verbatim proof — the model's reading of the code)")
        add("")
        inferred = [
            f"- `{chunk.get('citation')}`: system prompt chunk — {chunk.get('verify_detail') or ''}"
            for chunk in chunks
            if chunk.get("kind") != "verbatim" or not chunk.get("verified")
        ]
        inferred += [
            f"- `{tool.get('citation')}`: tool `{tool.get('name')}` schema "
            f"({tool.get('kind')})"
            for tool in data.get("tools") or []
            if tool.get("kind") != "verbatim" or not tool.get("verified")
        ]
        if generation:
            if generation.case_ids:
                inferred.append(
                    f"- every eval case: drafted from cited usage evidence, never verbatim "
                    f"({len(generation.case_ids)} case(s))"
                )
            inferred.append(
                f"- `backend.py`: {len(generation.implemented_tools)} re-implemented tool(s), "
                f"{len(generation.stub_tools)} stub(s) — semantics are never machine-verified"
            )
        add("\n".join(inferred) if inferred else "- (nothing)")
        add("")

        add("## Undetermined")
        add("")
        undetermined = data.get("undetermined") or []
        if undetermined:
            for item in undetermined:
                add(f"- **{item.get('what')}** — pointer: `{item.get('pointer')}` "
                    f"({item.get('why')})")
        else:
            add("- (the extraction reported no open questions; that is a claim too)")
        if generation and generation.dropped_cases:
            add("")
            add("Dropped drafts (kept out of the suite rather than guessed):")
            for case_id, why in generation.dropped_cases:
                add(f"- `{case_id}`: {why}")
        add("")

    # -- must review --------------------------------------------------------
    if generation:
        add("## Must review before a real run")
        add("")
        if generation.must_review:
            add(_table(
                [(f"`{item.file}`", item.lines, item.reason) for item in generation.must_review],
                ("file", "line(s)", "why"),
            ))
        else:
            add("- (nothing flagged — verify that yourself before believing it)")
        add("")
        if generation.notes:
            add("### Generation notes")
            add("")
            for note in generation.notes:
                add(f"- {note}")
            add("")

    # -- verification flags -------------------------------------------------
    if verification and verification.flags:
        add("## Verification gate")
        add("")
        ordered = sorted(verification.flags, key=lambda f: (f.severity != ERROR, f.artifact))
        add(_table(
            [(f.severity, f"`{f.artifact}`", f.what, f"`{f.citation or '-'}`", f.reason)
             for f in ordered],
            ("severity", "artifact", "claim", "citation", "what happened"),
        ))
        add("")

    # -- evidence -----------------------------------------------------------
    add("## Evidence the extraction saw")
    add("")
    add(f"{inventory.scanned_files} file(s) scanned · {inventory.candidate_files} with a "
        f"signal · {len(inventory.files)} ranked into the bundle · {len(inventory.slices)} "
        f"slice(s) · ~{inventory.evidence_tokens:,} tokens"
        + (" · **the token budget dropped slices**" if inventory.truncated else ""))
    if inventory.candidate_files > len(inventory.files):
        add("")
        add(f"{inventory.candidate_files - len(inventory.files)} lower-ranked file(s) were not "
            f"shown to the model (--max-files). If the agent's prompt or tools live in one of "
            f"them, raise the cap and re-run.")
    add("")
    add(_table(
        [
            (f"`{signal.path}`", f"{signal.score:g}", ", ".join(signal.reasons[:4]))
            for signal in inventory.files
        ],
        ("file", "score", "signals"),
    ))
    add("")
    if inventory.call_sites:
        add("Model call sites found:")
        add("")
        for site in inventory.call_sites[:12]:
            kwargs = ", ".join(f"{k}={v}" for k, v in list(site.kwargs.items())[:6])
            add(f"- `{site.citation}` `{site.callee}(` {kwargs} `)` [{site.how}]")
        add("")

    # -- extraction attempts + cost ----------------------------------------
    if extraction:
        add("## Extraction")
        add("")
        for attempt in extraction.attempts:
            status = "schema-valid" if attempt.ok else "REJECTED"
            add(f"- attempt {attempt.index}: {status}"
                + (f" — {'; '.join(attempt.errors[:5])}" if attempt.errors else ""))
        if not extraction.ok:
            add("- **the extraction never satisfied the schema**; artifacts above are salvage "
                "and should be treated as low confidence throughout")
        add("")
    if cost:
        add("## Cost")
        add("")
        usd = "unknown rate" if cost.usd is None else f"${cost.usd:.4f}"
        add(f"- {cost.input_tokens:,} input tokens (cached {cost.cached_input_tokens:,}) · "
            f"{cost.output_tokens:,} output tokens · **{usd}**")
        add(f"- recorded under `{cost.run_dir}` — priced by `upshift cost {cost.run_id}`")
        add("")

    # -- next steps ---------------------------------------------------------
    add("## Next")
    add("")
    add("```shell")
    add(f"# 1. read the must-review lines above, then edit {out_dir.name}/ by hand")
    add("# 2. free, deterministic pipeline check (no API key, no cost):")
    add(f"upshift upgrade --agent {out_dir} --provider sim \\")
    add("    --baseline-model sim-5.5 --candidate-model sim-5.6-sol --tag adapt-smoke")
    add("# 3. only then, the real thing (costs money):")
    add(f"upshift upgrade --agent {out_dir} --provider openai --flex \\")
    add("    --baseline-model gpt-5.5 --candidate-model gpt-5.6-sol --tag real")
    add("```")
    add("")
    return "\n".join(lines) + "\n"


def write_report(text: str, out_dir: Path) -> Path:
    path = Path(out_dir) / "ADAPT_REPORT.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
