"""Record-and-replay tool backend, generated by `upshift adapt --from-capture`.

Source capture: agents/capture-pydantic-ai-smoke/capture
Generated: 2026-09-06

Every result this returns was returned by the real tool, to the real framework, during the
capture. Nothing is re-implemented and nothing is invented: results are looked up by tool name
and by the canonical JSON of the arguments, exactly as recorded.

A call whose arguments were never recorded returns
`{"error": "no recorded result for these arguments"}`. That is deliberate. A repaired candidate that calls a tool with
new arguments has left the ground the capture covers, and a replay that quietly answered
anyway would turn "we do not know" into a passing case. It fails, visibly, and `state()`
lists every such call so the report shows exactly which ones they were.

Deterministic by construction (a pure lookup in a JSON file), as ADAPTER.md requires.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

NO_RECORD = "no recorded result for these arguments"

_RECORDED: dict[str, dict[str, Any]] = json.loads(
    (Path(__file__).resolve().parent / "recorded_tools.json").read_text(encoding="utf-8")
)


def canonical(arguments: Any) -> str:
    """The key the capture was written with (upshift.capture.record.canonical)."""
    return json.dumps(arguments, sort_keys=True, separators=(",", ":"), default=str)


class Backend:
    """Replays recorded tool results. Never raises, as ADAPTER.md requires."""

    def __init__(self, initial_state: dict[str, Any] | None = None) -> None:
        # `initial_state` is unused by design: a capture has no world to seed, only answers.
        self._calls: list[dict[str, Any]] = []
        self._unrecorded: list[dict[str, Any]] = []

    def execute(self, name: str, arguments: dict[str, Any]) -> dict[str, Any]:
        self._calls.append({"name": name, "arguments": arguments})
        by_arguments = _RECORDED.get(name)
        if by_arguments is None:
            return self._miss(name, arguments, f"the capture never recorded a call to {name!r}")
        key = canonical(arguments)
        if key in by_arguments:
            return copy.deepcopy(by_arguments[key])
        return self._miss(
            name, arguments,
            f"{name} was called in the capture, but never with these arguments",
        )

    def state(self) -> dict[str, Any]:
        return {"tool_calls": self._calls, "unrecorded_calls": self._unrecorded}

    def _miss(self, name: str, arguments: dict[str, Any], detail: str) -> dict[str, Any]:
        self._unrecorded.append({"name": name, "arguments": arguments})
        recorded = sorted(_RECORDED.get(name) or {})
        return {
            "error": NO_RECORD,
            "detail": detail,
            "tool": name,
            "recorded_argument_sets": recorded[:5],
        }


def create_backend(initial_state: dict[str, Any]) -> Backend:
    return Backend(initial_state)
